image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "-s .mvn/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.mvn/repository"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - '**/target/**.jar'
      - 'target/**.jar'
    exclude:
      - '.mvn/**'
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
  dependencies:
    - test
  when: always